name: manuscript_export
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - name: upgrade pip and install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -U pip setuptools
          pip install requests
          pip install beautifulsoup4
          pip install pandas
          pip install lxml
          pip install html5lib
      - name: output_render
        uses: jannekem/run-python-script-action@v1
        with:
          script: |

      - name: commit files
        continue-on-error: true
        run: |
          today=$(date +"%Y-%m-%d")
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "updated datasets ${today} UTC" -a
      - name: push changes
        continue-on-error: true
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
